[package]
name = "probable-eureka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
byteorder = "*"
hashbrown = "0.14.5"
rayon = "1.10.0"

[profile.release]
lto = true
codegen-units = 1